//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessiya3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Разговоры
    {
        public int Номер_разговора { get; set; }
        public Nullable<System.DateTime> Дата_разговора { get; set; }
        public Nullable<int> Продолжительность_разговора { get; set; }
        public Nullable<int> Код_города { get; set; }
        public Nullable<int> Код_телефона { get; set; }
    
        public virtual Города Города { get; set; }
        public virtual Телефон Телефон { get; set; }
    }
}
