//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessiya3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Телефон
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Телефон()
        {
            this.Абонент = new HashSet<Абонент>();
            this.Разговоры = new HashSet<Разговоры>();
        }
    
        public string Номер_телефона { get; set; }
        public string Номер_договора { get; set; }
        public Nullable<System.DateTime> Дата_установки_телефона { get; set; }
        public int Код_телефона { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Абонент> Абонент { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Разговоры> Разговоры { get; set; }
    }
}
